import Cabecalho from '@/components/Cabecalho'
import Cards from '@/components/Cards'
import Titulo from '@/components/Titulo'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Fazenda Organica</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Cabecalho />
      <Titulo titulo="Fazenda Orgânica" />
      <Cards />

    </>
  )
}
